[2022-02-02 10:01:43,681] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: twitter_dag.twitter_aluraonline 2022-01-31T09:00:00+00:00 [queued]>
[2022-02-02 10:01:43,700] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: twitter_dag.twitter_aluraonline 2022-01-31T09:00:00+00:00 [queued]>
[2022-02-02 10:01:43,700] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 10:01:43,700] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2022-02-02 10:01:43,700] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 10:01:43,718] {taskinstance.py:1115} INFO - Executing <Task(TwitterOperator): twitter_aluraonline> on 2022-01-31T09:00:00+00:00
[2022-02-02 10:01:43,722] {standard_task_runner.py:52} INFO - Started process 15513 to run task
[2022-02-02 10:01:43,739] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'twitter_dag', 'twitter_aluraonline', '2022-01-31T09:00:00+00:00', '--job-id', '38', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/var/folders/k6/528t8tnx5llf4w8y5xx1rrm80000gn/T/tmp3bp5cnb4', '--error-file', '/var/folders/k6/528t8tnx5llf4w8y5xx1rrm80000gn/T/tmphskv650m']
[2022-02-02 10:01:43,741] {standard_task_runner.py:77} INFO - Job 38: Subtask twitter_aluraonline
[2022-02-02 10:01:43,796] {logging_mixin.py:109} INFO - Running <TaskInstance: twitter_dag.twitter_aluraonline 2022-01-31T09:00:00+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2022-02-02 10:01:43,851] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=twitter_dag
AIRFLOW_CTX_TASK_ID=twitter_aluraonline
AIRFLOW_CTX_EXECUTION_DATE=2022-01-31T09:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-31T09:00:00+00:00
[2022-02-02 10:01:43,861] {base.py:79} INFO - Using connection to: id: twitter_default. Host: https://api.twitter.com, Port: None, Schema: , Login: , Password: None, extra: {'Authorization': '***'}
[2022-02-02 10:01:43,863] {twitter_hook.py:36} INFO - URL: https://api.twitter.com/2/tweets/search/recent?query=AluraOnline&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2022-01-31T09:00:00.00Z&end_time=2022-02-01T09:00:00.00Z
[2022-02-02 10:01:43,874] {local_task_job.py:151} INFO - Task exited with return code Negsignal.SIGABRT
[2022-02-02 10:01:43,893] {taskinstance.py:1513} INFO - Marking task as FAILED. dag_id=twitter_dag, task_id=twitter_aluraonline, execution_date=20220131T090000, start_date=20220202T130143, end_date=20220202T130143
[2022-02-02 10:01:43,934] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-02 10:56:07,298] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: twitter_dag.twitter_aluraonline 2022-01-31T09:00:00+00:00 [queued]>
[2022-02-02 10:56:07,315] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: twitter_dag.twitter_aluraonline 2022-01-31T09:00:00+00:00 [queued]>
[2022-02-02 10:56:07,315] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 10:56:07,315] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2022-02-02 10:56:07,315] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 10:56:07,328] {taskinstance.py:1115} INFO - Executing <Task(TwitterOperator): twitter_aluraonline> on 2022-01-31T09:00:00+00:00
[2022-02-02 10:56:07,331] {standard_task_runner.py:52} INFO - Started process 19708 to run task
[2022-02-02 10:56:07,345] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'twitter_dag', 'twitter_aluraonline', '2022-01-31T09:00:00+00:00', '--job-id', '6', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/var/folders/k6/528t8tnx5llf4w8y5xx1rrm80000gn/T/tmps_yw1gc2', '--error-file', '/var/folders/k6/528t8tnx5llf4w8y5xx1rrm80000gn/T/tmp88gn24g9']
[2022-02-02 10:56:07,347] {standard_task_runner.py:77} INFO - Job 6: Subtask twitter_aluraonline
[2022-02-02 10:56:07,398] {logging_mixin.py:109} INFO - Running <TaskInstance: twitter_dag.twitter_aluraonline 2022-01-31T09:00:00+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2022-02-02 10:56:07,459] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=twitter_dag
AIRFLOW_CTX_TASK_ID=twitter_aluraonline
AIRFLOW_CTX_EXECUTION_DATE=2022-01-31T09:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-31T09:00:00+00:00
[2022-02-02 10:56:07,473] {taskinstance.py:1463} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/bezerraescossia/Github/studies/twitter-project/.venv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1165, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/bezerraescossia/Github/studies/twitter-project/.venv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1283, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/bezerraescossia/Github/studies/twitter-project/.venv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1313, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/bezerraescossia/Github/studies/twitter-project/airflow/plugins/operators/twitter_operator.py", line 49, in execute
    for pg in hook.run():
  File "/Users/bezerraescossia/Github/studies/twitter-project/airflow/plugins/hooks/twitter_hook.py", line 52, in run
    session = self.get_conn()
  File "/Users/bezerraescossia/Github/studies/twitter-project/.venv/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 72, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/Users/bezerraescossia/Github/studies/twitter-project/.venv/lib/python3.7/site-packages/airflow/hooks/base.py", line 68, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/Users/bezerraescossia/Github/studies/twitter-project/.venv/lib/python3.7/site-packages/airflow/models/connection.py", line 379, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `twitter_default` isn't defined
[2022-02-02 10:56:07,478] {taskinstance.py:1513} INFO - Marking task as FAILED. dag_id=twitter_dag, task_id=twitter_aluraonline, execution_date=20220131T090000, start_date=20220202T135607, end_date=20220202T135607
[2022-02-02 10:56:07,526] {local_task_job.py:151} INFO - Task exited with return code 1
[2022-02-02 10:56:07,559] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-02 11:22:25,446] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: twitter_dag.twitter_aluraonline 2022-01-31T09:00:00+00:00 [queued]>
[2022-02-02 11:22:25,455] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: twitter_dag.twitter_aluraonline 2022-01-31T09:00:00+00:00 [queued]>
[2022-02-02 11:22:25,455] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 11:22:25,455] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2022-02-02 11:22:25,455] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 11:22:25,465] {taskinstance.py:1115} INFO - Executing <Task(TwitterOperator): twitter_aluraonline> on 2022-01-31T09:00:00+00:00
[2022-02-02 11:22:25,468] {standard_task_runner.py:52} INFO - Started process 22038 to run task
[2022-02-02 11:22:25,476] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'twitter_dag', 'twitter_aluraonline', '2022-01-31T09:00:00+00:00', '--job-id', '10', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/var/folders/k6/528t8tnx5llf4w8y5xx1rrm80000gn/T/tmpi0kv8kfg', '--error-file', '/var/folders/k6/528t8tnx5llf4w8y5xx1rrm80000gn/T/tmpg0u7_nko']
[2022-02-02 11:22:25,480] {standard_task_runner.py:77} INFO - Job 10: Subtask twitter_aluraonline
[2022-02-02 11:22:25,522] {logging_mixin.py:109} INFO - Running <TaskInstance: twitter_dag.twitter_aluraonline 2022-01-31T09:00:00+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2022-02-02 11:22:25,572] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=twitter_dag
AIRFLOW_CTX_TASK_ID=twitter_aluraonline
AIRFLOW_CTX_EXECUTION_DATE=2022-01-31T09:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-31T09:00:00+00:00
[2022-02-02 11:22:25,580] {base.py:79} INFO - Using connection to: id: twitter_default. Host: https://api.twitter.com, Port: None, Schema: , Login: , Password: None, extra: {'Authorization': '***'}
[2022-02-02 11:22:25,582] {twitter_hook.py:36} INFO - URL: https://api.twitter.com/2/tweets/search/recent?query=AluraOnline&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2022-01-31T09:00:00.00Z&end_time=2022-02-01T09:00:00.00Z
[2022-02-02 11:22:26,076] {twitter_hook.py:36} INFO - URL: https://api.twitter.com/2/tweets/search/recent?query=AluraOnline&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2022-01-31T09:00:00.00Z&end_time=2022-02-01T09:00:00.00Z&next_token=b26v89c19zqg8o3fpe48hb71b71bbb167pqksjkilahdp
[2022-02-02 11:22:26,348] {twitter_hook.py:36} INFO - URL: https://api.twitter.com/2/tweets/search/recent?query=AluraOnline&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2022-01-31T09:00:00.00Z&end_time=2022-02-01T09:00:00.00Z&next_token=b26v89c19zqg8o3fpe48hb5jd1il57c2jsppdh27dfon1
[2022-02-02 11:22:26,595] {twitter_hook.py:36} INFO - URL: https://api.twitter.com/2/tweets/search/recent?query=AluraOnline&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2022-01-31T09:00:00.00Z&end_time=2022-02-01T09:00:00.00Z&next_token=b26v89c19zqg8o3fpe48h92awrjyib8vyytmqpmly120t
[2022-02-02 11:22:26,867] {twitter_hook.py:36} INFO - URL: https://api.twitter.com/2/tweets/search/recent?query=AluraOnline&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2022-01-31T09:00:00.00Z&end_time=2022-02-01T09:00:00.00Z&next_token=b26v89c19zqg8o3fpe48h91epj2c6bew1umkophgnmph9
[2022-02-02 11:22:27,099] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=twitter_dag, task_id=twitter_aluraonline, execution_date=20220131T090000, start_date=20220202T142225, end_date=20220202T142227
[2022-02-02 11:22:27,125] {local_task_job.py:151} INFO - Task exited with return code 0
[2022-02-02 11:22:27,146] {local_task_job.py:261} INFO - 1 downstream tasks scheduled from follow-on schedule check
