[2022-01-31 18:05:16,292] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: twitter_dag.twitter_aluraonline 2022-01-30T09:00:00+00:00 [queued]>
[2022-01-31 18:05:16,302] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: twitter_dag.twitter_aluraonline 2022-01-30T09:00:00+00:00 [queued]>
[2022-01-31 18:05:16,302] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2022-01-31 18:05:16,303] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2022-01-31 18:05:16,303] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2022-01-31 18:05:16,313] {taskinstance.py:1115} INFO - Executing <Task(TwitterOperator): twitter_aluraonline> on 2022-01-30T09:00:00+00:00
[2022-01-31 18:05:16,316] {standard_task_runner.py:52} INFO - Started process 85313 to run task
[2022-01-31 18:05:16,326] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'twitter_dag', 'twitter_aluraonline', '2022-01-30T09:00:00+00:00', '--job-id', '31', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/var/folders/k6/528t8tnx5llf4w8y5xx1rrm80000gn/T/tmpbxy0lmxu', '--error-file', '/var/folders/k6/528t8tnx5llf4w8y5xx1rrm80000gn/T/tmpkxw464gb']
[2022-01-31 18:05:16,328] {standard_task_runner.py:77} INFO - Job 31: Subtask twitter_aluraonline
[2022-01-31 18:05:16,398] {logging_mixin.py:109} INFO - Running <TaskInstance: twitter_dag.twitter_aluraonline 2022-01-30T09:00:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-01-31 18:05:16,466] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=twitter_dag
AIRFLOW_CTX_TASK_ID=twitter_aluraonline
AIRFLOW_CTX_EXECUTION_DATE=2022-01-30T09:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-30T09:00:00+00:00
[2022-01-31 18:05:16,476] {base.py:79} INFO - Using connection to: id: twitter_default. Host: https://api.twitter.com, Port: None, Schema: , Login: , Password: None, extra: {'Authorization': '***'}
[2022-01-31 18:05:16,478] {twitter_hook.py:36} INFO - URL: https://api.twitter.com/2/tweets/search/recent?query=AluraOnline&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2022-01-30T09:00:00.00Z&end_time=2022-01-31T09:00:00.00Z
[2022-01-31 18:05:17,005] {twitter_hook.py:36} INFO - URL: https://api.twitter.com/2/tweets/search/recent?query=AluraOnline&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2022-01-30T09:00:00.00Z&end_time=2022-01-31T09:00:00.00Z&next_token=b26v89c19zqg8o3fpe482idqxzo42rpid6savzg5dcq65
[2022-01-31 18:05:17,281] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=twitter_dag, task_id=twitter_aluraonline, execution_date=20220130T090000, start_date=20220131T210516, end_date=20220131T210517
[2022-01-31 18:05:17,335] {local_task_job.py:151} INFO - Task exited with return code 0
[2022-01-31 18:05:17,384] {local_task_job.py:261} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-02-02 10:56:03,009] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: twitter_dag.twitter_aluraonline 2022-01-30T09:00:00+00:00 [queued]>
[2022-02-02 10:56:03,027] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: twitter_dag.twitter_aluraonline 2022-01-30T09:00:00+00:00 [queued]>
[2022-02-02 10:56:03,027] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 10:56:03,028] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2022-02-02 10:56:03,028] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 10:56:03,039] {taskinstance.py:1115} INFO - Executing <Task(TwitterOperator): twitter_aluraonline> on 2022-01-30T09:00:00+00:00
[2022-02-02 10:56:03,048] {standard_task_runner.py:52} INFO - Started process 19702 to run task
[2022-02-02 10:56:03,064] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'twitter_dag', 'twitter_aluraonline', '2022-01-30T09:00:00+00:00', '--job-id', '5', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/var/folders/k6/528t8tnx5llf4w8y5xx1rrm80000gn/T/tmphv13f0mm', '--error-file', '/var/folders/k6/528t8tnx5llf4w8y5xx1rrm80000gn/T/tmp32_d8gkh']
[2022-02-02 10:56:03,066] {standard_task_runner.py:77} INFO - Job 5: Subtask twitter_aluraonline
[2022-02-02 10:56:03,115] {logging_mixin.py:109} INFO - Running <TaskInstance: twitter_dag.twitter_aluraonline 2022-01-30T09:00:00+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2022-02-02 10:56:03,167] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=twitter_dag
AIRFLOW_CTX_TASK_ID=twitter_aluraonline
AIRFLOW_CTX_EXECUTION_DATE=2022-01-30T09:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-30T09:00:00+00:00
[2022-02-02 10:56:03,180] {taskinstance.py:1463} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/bezerraescossia/Github/studies/twitter-project/.venv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1165, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/bezerraescossia/Github/studies/twitter-project/.venv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1283, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/bezerraescossia/Github/studies/twitter-project/.venv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1313, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/bezerraescossia/Github/studies/twitter-project/airflow/plugins/operators/twitter_operator.py", line 49, in execute
    for pg in hook.run():
  File "/Users/bezerraescossia/Github/studies/twitter-project/airflow/plugins/hooks/twitter_hook.py", line 52, in run
    session = self.get_conn()
  File "/Users/bezerraescossia/Github/studies/twitter-project/.venv/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 72, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/Users/bezerraescossia/Github/studies/twitter-project/.venv/lib/python3.7/site-packages/airflow/hooks/base.py", line 68, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/Users/bezerraescossia/Github/studies/twitter-project/.venv/lib/python3.7/site-packages/airflow/models/connection.py", line 379, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `twitter_default` isn't defined
[2022-02-02 10:56:03,184] {taskinstance.py:1513} INFO - Marking task as FAILED. dag_id=twitter_dag, task_id=twitter_aluraonline, execution_date=20220130T090000, start_date=20220202T135603, end_date=20220202T135603
[2022-02-02 10:56:03,207] {local_task_job.py:151} INFO - Task exited with return code 1
[2022-02-02 10:56:03,234] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-02 11:21:59,747] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: twitter_dag.twitter_aluraonline 2022-01-30T09:00:00+00:00 [queued]>
[2022-02-02 11:21:59,754] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: twitter_dag.twitter_aluraonline 2022-01-30T09:00:00+00:00 [queued]>
[2022-02-02 11:21:59,755] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 11:21:59,755] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2022-02-02 11:21:59,755] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2022-02-02 11:21:59,765] {taskinstance.py:1115} INFO - Executing <Task(TwitterOperator): twitter_aluraonline> on 2022-01-30T09:00:00+00:00
[2022-02-02 11:21:59,768] {standard_task_runner.py:52} INFO - Started process 21990 to run task
[2022-02-02 11:21:59,777] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'twitter_dag', 'twitter_aluraonline', '2022-01-30T09:00:00+00:00', '--job-id', '8', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/var/folders/k6/528t8tnx5llf4w8y5xx1rrm80000gn/T/tmpblsj3tdh', '--error-file', '/var/folders/k6/528t8tnx5llf4w8y5xx1rrm80000gn/T/tmp7b2msmo2']
[2022-02-02 11:21:59,780] {standard_task_runner.py:77} INFO - Job 8: Subtask twitter_aluraonline
[2022-02-02 11:21:59,825] {logging_mixin.py:109} INFO - Running <TaskInstance: twitter_dag.twitter_aluraonline 2022-01-30T09:00:00+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2022-02-02 11:21:59,879] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=twitter_dag
AIRFLOW_CTX_TASK_ID=twitter_aluraonline
AIRFLOW_CTX_EXECUTION_DATE=2022-01-30T09:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-30T09:00:00+00:00
[2022-02-02 11:21:59,888] {base.py:79} INFO - Using connection to: id: twitter_default. Host: https://api.twitter.com, Port: None, Schema: , Login: , Password: None, extra: {'Authorization': '***'}
[2022-02-02 11:21:59,890] {twitter_hook.py:36} INFO - URL: https://api.twitter.com/2/tweets/search/recent?query=AluraOnline&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2022-01-30T09:00:00.00Z&end_time=2022-01-31T09:00:00.00Z
[2022-02-02 11:22:00,393] {twitter_hook.py:36} INFO - URL: https://api.twitter.com/2/tweets/search/recent?query=AluraOnline&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2022-01-30T09:00:00.00Z&end_time=2022-01-31T09:00:00.00Z&next_token=b26v89c19zqg8o3fpe482idqxzo42rpid6savzg5dcq65
[2022-02-02 11:22:00,621] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=twitter_dag, task_id=twitter_aluraonline, execution_date=20220130T090000, start_date=20220202T142159, end_date=20220202T142200
[2022-02-02 11:22:00,665] {local_task_job.py:151} INFO - Task exited with return code 0
[2022-02-02 11:22:00,689] {local_task_job.py:261} INFO - 1 downstream tasks scheduled from follow-on schedule check
